services:
  api:
    build: .
    ports:
      - "10000:8000"
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./model/:/app/models
      - ./ollama:/root/.ollama
